/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.

 

Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"
 

Constraints:

0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.
*/

impl Solution {
    pub fn find_the_difference(s: String, t: String) -> char {
        let mut ret = 0;
        for ch in s.bytes() {
            ret ^= ch;
        }
        for ch in t.bytes() {
            ret ^= ch;
        }
        
        ret as char
    }
}

